/*
 * CommGrid.cpp
 *
 *  Created on: Dec 29, 2016
 *      Author: arlind
 */

#include "grid/CommGrid.h"
#include <cmath>
#include "xml/xmlParser.h"



CommGrid::~CommGrid() {
	// TODO Autogenerated destructor stub
}
bool CommGrid::getSpeed(int x,int y,int* speed){
	*speed=(*repMatrix)(x,y);
	if(*speed==0){
		return false;
	}else{
		return true;
	}
}
void CommGrid::setSpeed(int xCenter,int yCenter,int speed){
	int starti,startj,endi,endj;
		if(xCenter-speed<0){
			starti=0;
		}else{
			starti=xCenter-speed;
		}
		if(yCenter-speed<0){
				startj=0;
			}else{
				startj=yCenter-speed;
		}
		if(xCenter+speed>=this->repMatrix->rows()){
				endi=this->repMatrix->rows()-1;
			}else{
				endi=xCenter+speed;
		}
		if(yCenter+speed>=this->repMatrix->cols()){
				endj=this->repMatrix->cols()-1;
			}else{
				endj=yCenter+speed;
		}

		//Given (X,Y), retrive all the eight-connected free cells
		for(int i = starti; i <= endi; i++)
		    for(int j = startj; j <= endj; j++)
		    {
		    	double xDist=(i-xCenter)*(i-xCenter);
		    	double yDist=(j-yCenter)*(j-yCenter);
		    	int distance=sqrt(xDist+yDist);
		    	int speedForCell=speed-distance;
		    	if(speedForCell>0){
		    	(*repMatrix)(i,j)=speedForCell;
		    	}
		    }

}
void CommGrid::setMatrix(std::vector<xml::antenna> antenne){
	for(xml::antenna a:antenne){
		setSpeed(a.first.first,a.first.second,a.second);
	}
}











